export async function GET() {
    const tickets = [
        // 1
        {id: 't-1816',
        title: 'Cannot log in to account',
        description: 'I no longer have access to my phone to verify account',
        priority:,
        status:,
        assignee:,
        updatedAt:},
        // 2
        {id: 't-1667',
        title: 'Printer in marketing room is not printing',
        description: 'Printer status says online but does not print',
        priority:,
        status:,
        assignee:,
        updatedAt:},
        // 3
        {id: 't-1928',
        title: 'New hire needs new laptop ASAP',
        description: 'New hire needs laptop with all company required software installed',
        priority:,
        status:,
        assignee:,
        updatedAt:},
        // 4
        {id: 't-1450',
        title: 'Slow wifi connection',
        description: 'It takes forever to open a new window and search online',
        priority:,
        status:,
        assignee:,
        updatedAt:},
        // 5
        {id: 't-1589',
        title: 'Monitor display not working',
        description: 'Monitor is connected but shows up a black screen',
        priority:,
        status:,
        assignee:,
        updatedAt:},
        // 6
        {id: 't-1892',
        title: 'Cannot access shared files for group project',
        description: 'It seems like I have no permissions to the shared folder and cannot access it',
        priority:,
        status:,
        assignee:,
        updatedAt:},
        // 7
        {id: 't-1275',
        title: 'Need password reset for email',
        description: 'I cannot remember my password but it will not let me reset password',
        priority:,
        status:,
        assignee:,
        updatedAt:},
        // 8
        {id: 't-1095',
        title: 'Audio issues with Teams meeting',
        description: 'My headphones are connected but I cannot hear any sound or voices from the meeting',
        priority:,
        status:,
        assignee:,
        updatedAt:},
        // 9
        {id: 't-1412',
        title: 'Calendar not updating',
        description: 'I cannot see what other people add to our shared calendar',
        priority:,
        status:,
        assignee:,
        updatedAt:},
        // 10
        {id: 't-1087',
        title: 'Projector not connecting to MacBook',
        description: 'Projector constantly disconnects from my MacBook and will not stay connected',
        priority:,
        status:,
        assignee:,
        updatedAt:},
        // 11
        {id: 't-1684',
        title: 'Cannot find Word document',
        description: 'I keep saving my word documents but I cannot find them where I saved them',
        priority:,
        status:,
        assignee:,
        updatedAt:},
        // 12
        {id: 't-1700',
        title: 'PC is not turning on',
        description: 'PC is connected but it does not turn on when I click button',
        priority:,
        status:,
        assignee:,
        updatedAt:},
        // 13
        {id: 't-1077',
        title: 'Teams chat not showing up',
        description: 'I hear the notification sound from Teams for a new message but I see no new message in chat',
        priority:,
        status:,
        assignee:,
        updatedAt:},
    ]
}